stages:
  - test
  - package
  - deploy

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - /var/cache/yum

flake8_linter:
  stage: test
  image: python:2.7
  script:
  - pip install tox
  - tox -e flake8

unittests:
  stage: test
  image: python:2.7
  script:
  - pip install tox
  - tox -e unit

integrationtests:
  stage: test
  image: python:2.7
  script:
  - pip install tox
  - tox -e integration

package:
  stage: package
  image: ari-apc-lab/croupier-cli
  script:
  - DIR=${PWD##*/} && cd .. && zip -r $DIR/croupier_plugin.zip $DIR -x $DIR/.\* && cd $DIR
  - wagon create croupier_plugin.zip -a '--no-cache-dir -c constraints.txt'
  - PLUGIN_NAME=$(echo *.wgn | awk -F- '{print $1}')
  - PLUGIN_VERSION=$(echo *.wgn | awk -F- '{print $2}')
  artifacts:
    name: $PLUGIN_NAME-$PLUGIN_VERSION
    paths:
    - "*.wgn"
    expire_in: 1 hour
  only:
    - master
    - production

deploy:staging:
  stage: deploy
  image: ari-apc-lab/croupier-cli
  dependencies:
  - package
  script:
  - cfy profile use $ORCHESTRATOR_HOST -t default_tenant -u admin -p $ORCHESTRATOR_ADMIN_PASSWD
  - PLUGIN_NAME=$(echo *.wgn | awk -F- '{print $1}')
  - PLUGIN_VERSION=$(echo *.wgn | awk -F- '{print $2}')
  - EXISTS=$(cfy plugins list | grep -E "$PLUGIN_NAME( )*\|( )*$PLUGIN_VERSION")
  - if [ ! -z "$EXISTS" ]; then PLUGIN_ID=$(echo $EXISTS | awk -F'| ' '{print $2}'); cfy plugins delete $PLUGIN_ID; fi
  - cfy plugins upload *.wgn -y plugin.yaml -t default_tenant
  environment:
    name: staging
    url: http://portal.croupier.com
  only:
    - master

deploy:production:
  stage: deploy
  image: ari-apc-lab/croupier-cli
  dependencies:
  - package
  script:
  - cfy profile use $ORCHESTRATOR_HOST -t default_tenant -u admin -p $ORCHESTRATOR_ADMIN_PASSWD
  - PLUGIN_NAME=$(echo *.wgn | awk -F- '{print $1}')
  - PLUGIN_VERSION=$(echo *.wgn | awk -F- '{print $2}')
  - EXISTS=$(cfy plugins list | grep -E "$PLUGIN_NAME( )*\|( )*$PLUGIN_VERSION")
  - if [ ! -z "$EXISTS" ]; then PLUGIN_ID=$(echo $EXISTS | awk -F'| ' '{print $2}'); cfy plugins delete $PLUGIN_ID; fi
  - cfy plugins upload *.wgn -y plugin.yaml -t default_tenant
  environment:
    name: production
    url: http://portal.croupier.com
  artifacts:
    name: CI_COMMIT_REF_NAME
    paths:
    - "*.wgn"
  only:
    - tags
