########
# Copyright (c) 2019 Atos Spain SA. All rights reserved.
#
# This file is part of Croupier.
#
# Croupier is free software: you can redistribute it and/or modify it
# under the terms of the Apache License, Version 2.0 (the License) License.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT ANY WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT, IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
# OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# See README file for full disclaimer information and LICENSE file for full
# license information in the project root.
#
# @author: Javier Carnero
#          Atos Research & Innovation, Atos Spain S.A.
#          e-mail: javier.carnero@atos.net
#
# plugin.yaml

plugins:
    croupier:
        executor: central_deployment_agent

        # URL to archive containing the plugin or name of directory containing
        # the plugin if it is included in the the blueprint directory under the
        # "plugins" directory.
        source: https://github.com/ari-apc-lab/croupier/archive/master.zip
        package_name: croupier-plugin
        package_version: "2.3.0"

workflows:
    run_jobs:
        mapping: croupier.croupier_plugin.workflows.run_jobs

node_types:
    croupier.nodes.InfrastructureInterface:
        derived_from: cloudify.nodes.Compute
        properties:
            config:
                description: type, and optionally timezone
            credentials:
                description: SSH credentials
            external_monitor_entrypoint:
                description: Monitor entrypoint, port and orchestrator port
                default: ""
                type: string
            external_monitor_port:
                description: Monitor entrypoint, port and orchestrator port
                default: ":9090"
                type: string
            external_monitor_type:
                description: Monitor type, e.g PROMETHEUS
                default: "PROMETHEUS"
                type: string
            external_monitor_orchestrator_port:
                description: Monitor entrypoint, port and orchestrator port
                default: ":8079"
                type: string
            job_prefix:
                description: Job name prefix for this HPC
                default: "croupier"
                type: string
            base_dir:
                description: Root directory of all executions
                default: "$HOME"
                type: string
            workdir_prefix:
                description: Prefix of the working directory instead of blueprint name
                default: ""
                type: string
            monitor_period:
                description: Seconds to check job status.
                default: 60
                type: integer
            simulate:
                description: Set to true to simulate job without sending it
                type: boolean
                default: False
            skip_cleanup:
                description: True to not clean all files at deployment removal
                type: boolean
                default: False
            agent_config:
                default:
                    install_method: none
        interfaces:
            cloudify.interfaces.lifecycle:
                configure:
                    implementation: croupier.croupier_plugin.tasks.configure_execution
                    inputs:
                        config:
                            default: { get_property: [SELF, config] }
                        credentials:
                            default: { get_property: [SELF, credentials] }
                        base_dir:
                            default: { get_property: [SELF, base_dir] }
                        workdir_prefix:
                            default: { get_property: [SELF, workdir_prefix] }
                        simulate:
                            default: { get_property: [SELF, simulate] }
                delete:
                    implementation: croupier.croupier_plugin.tasks.cleanup_execution
                    inputs:
                        config:
                            default: { get_property: [SELF, config] }
                        credentials:
                            default: { get_property: [SELF, credentials] }
                        skip:
                            default: { get_property: [SELF, skip_cleanup] }
                        simulate:
                            default: { get_property: [SELF, simulate] }
            cloudify.interfaces.monitoring:
                start:
                    implementation: croupier.croupier_plugin.tasks.start_monitoring_hpc
                    inputs:
                        config:
                            default: { get_property: [SELF, config] }
                        credentials:
                            default: { get_property: [SELF, credentials] }
                        external_monitor_entrypoint:
                            default:
                                {
                                    get_property:
                                        [SELF, external_monitor_entrypoint],
                                }
                        external_monitor_port:
                            default:
                                { get_property: [SELF, external_monitor_port] }
                        external_monitor_orchestrator_port:
                            default:
                                {
                                    get_property:
                                        [
                                            SELF,
                                            external_monitor_orchestrator_port,
                                        ],
                                }
                        simulate:
                            default: { get_property: [SELF, simulate] }
                stop:
                    implementation: croupier.croupier_plugin.tasks.stop_monitoring_hpc
                    inputs:
                        config:
                            default: { get_property: [SELF, config] }
                        credentials:
                            default: { get_property: [SELF, credentials] }
                        external_monitor_entrypoint:
                            default:
                                {
                                    get_property:
                                        [SELF, external_monitor_entrypoint],
                                }
                        external_monitor_port:
                            default:
                                { get_property: [SELF, external_monitor_port] }
                        external_monitor_orchestrator_port:
                            default:
                                {
                                    get_property:
                                        [
                                            SELF,
                                            external_monitor_orchestrator_port,
                                        ],
                                }
                        simulate:
                            default: { get_property: [SELF, simulate] }

    croupier.nodes.Job:
        derived_from: cloudify.nodes.Root
        properties:
            deployment:
                description: Deployment script and inputs
                default: {}
            job_options:
                description: Job main command and options
            publish:
                description: Config to publish its outputs
                default: []
            skip_cleanup:
                description: True to not clean after execution (debug purposes)
                type: boolean
                default: False
        interfaces:
            cloudify.interfaces.lifecycle:
                start: # needs to be 'start' to have the wm credentials
                    implementation: croupier.croupier_plugin.tasks.bootstrap_job
                    inputs:
                        deployment:
                            description: Deployment scripts and inputs
                            default: { get_property: [SELF, deployment] }
                        skip_cleanup:
                            default: { get_property: [SELF, skip_cleanup] }
                stop:
                    implementation: croupier.croupier_plugin.tasks.revert_job
                    inputs:
                        deployment:
                            description: Undeployment script and inputs
                            default: { get_property: [SELF, deployment] }
                        skip_cleanup:
                            default: { get_property: [SELF, skip_cleanup] }
            croupier.interfaces.lifecycle:
                queue:
                    implementation: croupier.croupier_plugin.tasks.send_job
                    inputs:
                        job_options:
                            default: { get_property: [SELF, job_options] }
                publish:
                    implementation: croupier.croupier_plugin.tasks.publish
                    inputs:
                        publish_list:
                            default: { get_property: [SELF, publish] }
                cleanup:
                    implementation: croupier.croupier_plugin.tasks.cleanup_job
                    inputs:
                        job_options:
                            default: { get_property: [SELF, job_options] }
                        skip:
                            default: { get_property: [SELF, skip_cleanup] }
                cancel:
                    implementation: croupier.croupier_plugin.tasks.stop_job
                    inputs:
                        job_options:
                            default: { get_property: [SELF, job_options] }

    croupier.nodes.SingularityJob:
        derived_from: croupier.nodes.Job

relationships:
    interface_contained_in:
        derived_from: cloudify.relationships.contained_in
        source_interfaces:
            cloudify.interfaces.relationship_lifecycle:
                preconfigure:
                    implementation: croupier.croupier_plugin.tasks.preconfigure_interface
                    inputs:
                        config:
                            default: { get_property: [SOURCE, config] }
                        credentials:
                            default: { get_property: [SOURCE, credentials] }
                        simulate:
                            default: { get_property: [SOURCE, simulate] }
    job_managed_by_interface:
        derived_from: cloudify.relationships.contained_in
        source_interfaces:
            cloudify.interfaces.relationship_lifecycle:
                preconfigure:
                    implementation: croupier.croupier_plugin.tasks.preconfigure_job
                    inputs:
                        config:
                            default: { get_property: [TARGET, config] }
                        credentials:
                            default: { get_property: [TARGET, credentials] }
                        external_monitor_entrypoint:
                            default:
                                {
                                    get_property:
                                        [TARGET, external_monitor_entrypoint],
                                }
                        external_monitor_port:
                            default:
                                {
                                    get_property:
                                        [TARGET, external_monitor_port],
                                }
                        external_monitor_type:
                            default:
                                {
                                    get_property:
                                        [TARGET, external_monitor_type],
                                }
                        external_monitor_orchestrator_port:
                            default:
                                {
                                    get_property:
                                        [
                                            TARGET,
                                            external_monitor_orchestrator_port,
                                        ],
                                }
                        job_prefix:
                            default: { get_property: [TARGET, job_prefix] }
                        monitor_period:
                            default: { get_property: [TARGET, monitor_period] }
                        simulate:
                            default: { get_property: [TARGET, simulate] }
    job_depends_on:
        derived_from: cloudify.relationships.depends_on
