{
 "title": "Croupier User's Dashboard (SLURM)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "user", "label": "HPC User", "query": "bsc08642,yosu" },
   {
    "name": "deployment_label",
    "query": "label_values(slurm_job_state{job_user=\"bsc08642\"},deployment_label)"
   },
   {
    "name": "job_id",
    "query": "label_values(slurm_partition_availability{deployment_label=\"$deployment_label\"}, job_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Workflow Executions for user $user",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "max (slurm_job_state{job_user=\"$user\"}) by (deployment_label)",
     "legendFormat": "{{deployment_label}}"
    }
   ]
  },
  {
   "title": "Job Executions  $deployment_label",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "slurm_job_cpu_n{deployment_label=\"$deployment_label\"}",
     "legendFormat": "{{deployment_label}}"
    },
    {
     "expr": "slurm_job_state{deployment_label=\"$deployment_label\"}",
     "legendFormat": "{{deployment_label}}"
    },
    {
     "expr": "slurm_job_walltime_used{deployment_label=\"$deployment_label\"}",
     "legendFormat": "{{deployment_label}}"
    },
    {
     "expr": "slurm_job_queued{deployment_label=\"$deployment_label\"}",
     "legendFormat": "{{deployment_label}}"
    },
    {
     "expr": "slurm_job_memory_virtual_max{deployment_label=\"$deployment_label\"}",
     "legendFormat": "{{deployment_label}}"
    },
    {
     "expr": "slurm_job_memory_physical_max{deployment_label=\"$deployment_label\"}",
     "legendFormat": "{{deployment_label}}"
    },
    {
     "expr": "slurm_job_exit_code{deployment_label=\"$deployment_label\"}"
    },
    {
     "expr": "slurm_job_exit_signal{deployment_label=\"$deployment_label\"}"
    }
   ]
  },
  {
   "title": "Job State ($job_id)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slurm_job_state{deployment_label=\"$deployment_label\",job_id=~\"$job_id\"}",
     "legendFormat": "$job_id"
    }
   ]
  },
  {
   "title": "Virtual Memory ($job_id)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "slurm_job_memory_virtual_max{deployment_label=\"$deployment_label\",job_id=~\"$job_id\"}",
     "legendFormat": "Virtual Memory"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 13, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "slurm_job_memory_physical_max{deployment_label=\"$deployment_label\",job_id=~\"$job_id\"}"
    }
   ]
  },
  {
   "title": "Job walltime used ($job_id)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_job_walltime_used{deployment_label=\"$deployment_label\",job_id=~\"$job_id\"}",
     "legendFormat": "$job_id"
    }
   ]
  }
 ]
}