{
 "title": "HPC PBS clusters",
 "description": "Dashboard provides details about available HPC PBS clusters and queues",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hpc",
    "label": "HPC Cluster",
    "query": "label_values(pbs_queue_enabled, hpc)"
   },
   {
    "name": "partition",
    "query": "label_values(slurm_partition_availability{hpc=\"$hpc\"}, partition)"
   }
  ]
 },
 "panels": [
  {
   "title": "Partitions for cluster $hpc",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pbs_queue_enabled{hpc=\"$hpc\"}"
    },
    {
     "expr": "pbs_queue_priority{hpc=\"$hpc\"}"
    },
    {
     "expr": "pbs_queue_avail_nodes{hpc=\"$hpc\"}"
    },
    {
     "expr": "pbs_queue_min_nodes{hpc=\"$hpc\"}"
    },
    {
     "expr": "pbs_queue_max_nodes{hpc=\"$hpc\"}"
    },
    {
     "expr": "pbs_queue_max_walltime{hpc=\"$hpc\"}"
    }
   ]
  },
  {
   "title": "#Assigned nodes in partition $partition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pbs_queue_assign_nodes{queue_name=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "#assigned nodes"
    }
   ]
  },
  {
   "title": "#Assigned CPUs in partition $partition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pbs_queue_assign_cpus{queue_name=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "#assigned CPUs"
    }
   ]
  },
  {
   "title": "Queued Nodes in partition $partition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pbs_queue_jobs_queued{queue_name=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "# Queued jobs"
    }
   ]
  },
  {
   "title": "Running jobs in partition $partition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pbs_queue_jobs_running{queue_name=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "# running jobs"
    }
   ]
  },
  {
   "title": "Total jobs in partition $partition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pbs_queue_jobs_total{queue_name=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "# total jobs"
    }
   ]
  }
 ]
}