{
 "title": "HPC SLURM clusters",
 "description": "Dashboard provides details about available HPC SLURM clusters and partitions",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hpc",
    "label": "HPC Cluster",
    "query": "label_values(slurm_partition_availability, hpc)"
   },
   {
    "name": "partition",
    "query": "label_values(slurm_partition_availability{hpc=\"$hpc\"}, partition)"
   }
  ]
 },
 "panels": [
  {
   "title": "Partitions for cluster $hpc",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "slurm_partition_availability{hpc=\"$hpc\"}"
    },
    {
     "expr": "slurm_partition_nodes{hpc=\"$hpc\"}"
    },
    {
     "expr": "slurm_partition_cpus{hpc=\"$hpc\"}"
    },
    {
     "expr": "slurm_partition_cores{hpc=\"$hpc\"}"
    },
    {
     "expr": "slurm_partition_job_size_lower{hpc=\"$hpc\"}"
    },
    {
     "expr": "slurm_partition_job_size_upper{hpc=\"$hpc\"}"
    },
    {
     "expr": "slurm_partition_memory{hpc=\"$hpc\"}"
    },
    {
     "expr": "slurm_partition_time_limit{hpc=\"$hpc\"}"
    }
   ]
  },
  {
   "title": "#Running/Pending jobs in partition $partition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slurm_partition_running_jobs{partition=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "#running jobs"
    },
    {
     "expr": "slurm_partition_pending_jobs{partition=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "#pending jobs"
    }
   ]
  },
  {
   "title": "Total/Allocated/Idle Nodes in partition $partition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slurm_partition_node_total{partition=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "Total nodes"
    },
    {
     "expr": "slurm_partition_node_alloc{partition=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "Allocated nodes"
    },
    {
     "expr": "slurm_partition_node_idle{partition=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "Idle nodes"
    }
   ]
  },
  {
   "title": "CPU load in partition $partition",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slurm_partition_cpus_load_lower{partition=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "Lower load"
    },
    {
     "expr": "slurm_partition_cpus_load_upper{partition=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "Upper load"
    }
   ]
  },
  {
   "title": "Free/Allocated Memory in partition $partition",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "slurm_partition_free_mem_lower{partition=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "Lower free memory"
    },
    {
     "expr": "slurm_partition_free_mem_upper{partition=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "Upper free memory"
    },
    {
     "expr": "slurm_partition_alloc_mem{partition=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "Allocated memory"
    }
   ]
  },
  {
   "title": "Queue/Execution/Left time per job in partition $partition",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "slurm_partition_queue_time_per_job{partition=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "Queue tme per job"
    },
    {
     "expr": "slurm_partition_execution_time_per_job{partition=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "Execution time per job"
    },
    {
     "expr": "slurm_partition_time_left_per_job{partition=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "Time left per job"
    }
   ]
  },
  {
   "title": "Min requested/Max allocated nodes per job in partition $partition",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slurm_partition_minimum_requested_nodes_per_job{partition=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "Min requested nodes per job"
    },
    {
     "expr": "slurm_partition_maximum_allocated_nodes_per_job{partition=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "Max allocated nodes per job"
    }
   ]
  },
  {
   "title": "Min requested/Max allocated CPUs per job in partition $partition",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slurm_partition_minimum_requested_cpus_per_job{partition=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "Min requested CPUs per job "
    },
    {
     "expr": "slurm_partition_maximum_allocated_cpus_per_job{partition=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "Max allocated CPUs per job"
    }
   ]
  },
  {
   "title": "Min requested Memory per job in partition $partition",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "slurm_partition_minimum_requested_memory_per_job{partition=\"$partition\", hpc=\"$hpc\"}",
     "legendFormat": "Min requested memory per job "
    }
   ]
  }
 ]
}